---
- name: Downloading and enable the EPEL repository definitions.
  yum: name=http://download.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

- name: Install Docker
  yum: pkg=docker-io state=present

- name: Start service
  service: name=docker state=started
